TEST_NAMES = [
    "WBC",
    "WhiteBloodCells",
    "White Blood Cells",
    "RBC",
    "RedBloodCells",
    "Red Blood Cells",
    "HGB",
    "Hb",
    "Hemoglobin",
    "HCT",
    "Hematocrit",
    "PLT",
    "Platelet",
    "Platelets",
    "MCV",
    "MCH",
    "MCHC",
    "RDW",
    "RDW-CV",
    "RDW-SD",
    "Neutrophils",
    "Neuts",
    "Lymphocytes",
    "Lymphs",
    "Monocytes",
    "Mono",
    "Eosinophils",
    "Eos",
    "Basophils",
    "Baso",
    "Absolute Neutrophil Count",
    "ANC",
    "MPV",
    "Mean Platelet Volume",
    "PDW",
    "P-LCR",
    "HemogIobin",
    "Hemog1obin",
    "Piatelets",
    "WBC.",
    "RBC.",
    "PLT.",
    "W.B.C",
    "R.B.C",
    "P.L.T",
    "Hgb",
    "Hct",
    "MCVfL",
    "Neutrophil",
    "Lymphocyte",
    "Eosinophil",
    "Basophil",
    "PT",
    "Prothrombin Time",
    "INR",
    "International Normalized Ratio",
    "aPTT",
    "PTT",
    "Activated Partial Thromboplastin Time",
    "Partial Thromboplastin Time",
    "Fibrinogen",
    "D-Dimer",
    "D Dimer",
    "DDimer",
    "Factor VIII",
    "Factor IX",
    "Bleeding Time",
    "Clotting Time",
    "Thrombin Time",
    "TT",
    "Protein C",
    "Protein S",
    "Antithrombin III",
    "ATIII",
    "Lupus Anticoagulant",
    "LA",
    "Glucose",
    "FBS",
    "Fasting Blood Sugar",
    "Blood Sugar",
    "Random Glucose",
    "RBS",
    "Postprandial Glucose",
    "PPBS",
    "HbA1c",
    "Glycated Hemoglobin",
    "A1c",
    "Urea",
    "BUN",
    "Blood Urea Nitrogen",
    "Creatinine",
    "Cr",
    "eGFR",
    "Estimated Glomerular Filtration Rate",
    "Sodium",
    "Na",
    "Potassium",
    "K",
    "Chloride",
    "Cl",
    "Bicarbonate",
    "CO2",
    "Total CO2",
    "Calcium",
    "Ca",
    "Ionized Calcium",
    "iCa",
    "Magnesium",
    "Mg",
    "Phosphorus",
    "Phosphate",
    "Phos",
    "AST",
    "SGOT",
    "ALT",
    "SGPT",
    "ALP",
    "Alkaline Phosphatase",
    "GGT",
    "Gamma Glutamyl Transferase",
    "LDH",
    "Lactate Dehydrogenase",
    "Bilirubin",
    "Total Bilirubin",
    "Direct Bilirubin",
    "Conjugated Bilirubin",
    "Indirect Bilirubin",
    "Unconjugated Bilirubin",
    "Albumin",
    "Total Protein",
    "Globulin",
    "A/G Ratio",
    "Cholesterol",
    "Total Cholesterol",
    "Triglycerides",
    "TG",
    "HDL",
    "HDL Cholesterol",
    "LDL",
    "LDL Cholesterol",
    "VLDL",
    "Non-HDL Cholesterol",
    "Uric Acid",
    "UA",
    "CPK",
    "Creatine Phosphokinase",
    "CK",
    "CK-MB",
    "Troponin I",
    "Troponin T",
    "Myoglobin",
    "BNP",
    "NT-proBNP",
    "Amylase",
    "Lipase",
    "Iron",
    "Total Iron Binding Capacity",
    "TIBC",
    "Transferrin",
    "Unsaturated Iron Binding Capacity",
    "UIBC",
    "Lactate",
    "Lactic Acid",
    "Osmolality",
    "Anion Gap",
    "TSH",
    "Thyroid Stimulating Hormone",
    "T3",
    "Triiodothyronine",
    "Total T3",
    "T4",
    "Thyroxine",
    "Total T4",
    "Free T3",
    "FT3",
    "Free T4",
    "FT4",
    "Reverse T3",
    "rT3",
    "Thyroid Peroxidase Antibodies",
    "TPO Antibodies",
    "TPOAb",
    "Thyroglobulin Antibodies",
    "TgAb",
    "Thyroid Stimulating Immunoglobulin",
    "TSI",
    "FSH",
    "Follicle Stimulating Hormone",
    "LH",
    "Luteinizing Hormone",
    "Prolactin",
    "PRL",
    "Testosterone",
    "Total Testosterone",
    "Free Testosterone",
    "Estradiol",
    "E2",
    "Estrogen",
    "Progesterone",
    "Cortisol",
    "AM Cortisol",
    "PM Cortisol",
    "ACTH",
    "Adrenocorticotropic Hormone",
    "Insulin",
    "C-Peptide",
    "Vitamin D",
    "25-OH Vitamin D",
    "25-Hydroxy Vitamin D",
    "Vitamin B12",
    "Cobalamin",
    "Folate",
    "Folic Acid",
    "Ferritin",
    "PSA",
    "Prostate Specific Antigen",
    "Free PSA",
    "Total PSA",
    "hCG",
    "Beta hCG",
    "Human Chorionic Gonadotropin",
    "Parathyroid Hormone",
    "PTH",
    "Calcitonin",
    "Aldosterone",
    "Renin",
    "DHEA-S",
    "Dehydroepiandrosterone Sulfate",
    "Color",
    "Appearance",
    "Clarity",
    "pH",
    "Specific Gravity",
    "SG",
    "Gravity",
    "Protein",
    "Albumin",
    "Glucose (Urine)",
    "Ketones",
    "Ketone",
    "Blood (Urine)",
    "Hemoglobin (Urine)",
    "Nitrite",
    "Leukocyte Esterase",
    "LE",
    "WBC (Urine)",
    "White Blood Cells (Urine)",
    "RBC (Urine)",
    "Red Blood Cells (Urine)",
    "Bacteria",
    "Yeast",
    "Epithelial Cells",
    "Squamous Epithelial Cells",
    "Transitional Epithelial Cells",
    "Renal Tubular Epithelial Cells",
    "Casts",
    "Hyaline Casts",
    "Granular Casts",
    "WBC Casts",
    "RBC Casts",
    "Crystals",
    "Calcium Oxalate",
    "Uric Acid Crystals",
    "Triple Phosphate",
    "Urobilinogen",
    "Bilirubin (Urine)",
    "Microalbumin",
    "Creatinine (Urine)",
    "Urine Creatinine",
    "Protein/Creatinine Ratio",
    "Microalbumin/Creatinine Ratio",
    "ACR",
    "UACR",
    "CRP",
    "C-Reactive Protein",
    "High Sensitivity CRP",
    "hs-CRP",
    "ESR",
    "Erythrocyte Sedimentation Rate",
    "Sed Rate",
    "Rheumatoid Factor",
    "RF",
    "Anti-CCP",
    "Cyclic Citrullinated Peptide",
    "ANA",
    "Antinuclear Antibody",
    "Anti-dsDNA",
    "Complement C3",
    "Complement C4",
    "CH50",
    "Total Hemolytic Complement",
    "IgG",
    "IgA",
    "IgM",
    "IgE",
    "Immunoglobulins",
    "HIV Antibody",
    "HIV Ag/Ab",
    "Hepatitis B Surface Antigen",
    "HBsAg",
    "Hepatitis B Surface Antibody",
    "Anti-HBs",
    "Hepatitis B Core Antibody",
    "Anti-HBc",
    "Hepatitis C Antibody",
    "Anti-HCV",
    "HCV RNA",
    "VDRL",
    "RPR",
    "ASO",
    "Antistreptolysin O",
    "Anti-TPO",
    "Tissue Transglutaminase Antibody",
    "tTG IgA",
    "CEA",
    "Carcinoembryonic Antigen",
    "CA-125",
    "CA 125",
    "CA-19-9",
    "CA 19-9",
    "CA-15-3",
    "CA 15-3",
    "AFP",
    "Alpha Fetoprotein",
    "Beta hCG",
    "Calcitonin",
    "Chromogranin A",
    "Neuron Specific Enolase",
    "NSE",
    "S-100",
    "HE4",
    "Human Epididymis Protein 4",
    "Gram Stain",
    "Culture and Sensitivity",
    "C&S",
    "Blood Culture",
    "Urine Culture",
    "Sputum Culture",
    "Wound Culture",
    "Stool Culture",
    "CSF Culture",
    "No Growth",
    "Growth",
    "Mixed Flora",
    "Gram Positive Cocci",
    "Gram Negative Rods",
    "Yeast",
    "Fungus",
    "MRSA Screen",
    "VRE Screen",
    "Clostridium difficile Toxin",
    "C diff Toxin",
    "Stool Ova and Parasite",
    "O&P",
    "Giardia Antigen",
    "Cryptosporidium Antigen",
    "Serum",
    "Plasma",
    "Whole Blood",
    "EDTA Blood",
    "Citrate Blood",
    "Heparinized Blood",
    "Urine",
    "Random Urine",
    "First Morning Urine",
    "24-hour Urine",
    "Clean Catch Urine",
    "Midstream Urine",
    "CSF",
    "Cerebrospinal Fluid",
    "Stool",
    "Feces",
    "Sputum",
    "Throat Swab",
    "Nasopharyngeal Swab",
    "Blood Culture Bottle",
    "Aerobic Bottle",
    "Anaerobic Bottle",
    "Wound Swab",
    "Tissue",
    "Biopsy",
    "Synovial Fluid",
    "Pleural Fluid",
    "Ascitic Fluid",
    "Pericardial Fluid",
    "Semen",
    "Saliva",
    "Sweat",
    "HemogIobin",
    "Hemog1obin",
    "Hem0globin",
    "Piatelets",
    "PlateIets",
    "Plate1ets",
    "WBC.",
    "RBC.",
    "PLT.",
    "W.B.C",
    "R.B.C",
    "P.L.T",
    "Hgb",
    "Hct",
    "MCVfL",
    "Neutrophil",
    "Lymphocyte",
    "Eosinophil",
    "Basophil",
    "Gluc0se",
    "GlucOse",
    "Glucose",
    "F8S",
    "FB5",
    "Urea",
    "Ure4",
    "Creatinine",
    "Creat1nine",
    "Creatin1ne",
    "S0dium",
    "Sod1um",
    "Potass1um",
    "P0tassium",
    "Chl0ride",
    "Chlor1de",
    "Ca1cium",
    "Calciurn",
    "Magnes1um",
    "Ph0sphorus",
    "Phosph0rus",
    "AST",
    "A5T",
    "ALT",
    "A1T",
    "ALP",
    "A1P",
    "Bilirubin",
    "Bilirub1n",
    "Bil1rubin",
    "Albumin",
    "A1bumin",
    "Cholesterol",
    "Cholester0l",
    "Triglycerides",
    "Triglycer1des",
    "HDL",
    "LDL",
    "VLDL",
    "Uric Acid",
    "Ur1c Acid",
    "TSH",
    "T5H",
    "Free T3",
    "Free T4",
    "FSH",
    "F5H",
    "LH",
    "LFI",
    "Prolactin",
    "Pr0lactin",
    "Testosterone",
    "Test0sterone",
    "Estradiol",
    "Estrad1ol",
    "Progesterone",
    "Pr0gesterone",
    "Cortisol",
    "C0rtisol",
    "Insulin",
    "Insu1in",
    "Vitamin D",
    "V1tamin D",
    "Vitamin B12",
    "Vitarnin B12",
    "Ferritin",
    "Ferr1tin",
    "PSA",
    "P5A",
    "Color",
    "Colour",
    "Appearance",
    "Apperance",
    "Clarity",
    "CIarity",
    "pH",
    "PH",
    "Specific Gravity",
    "Spec1fic Gravity",
    "Gravity",
    "Grav1ty",
    "Protein",
    "Pr0tein",
    "Glucose (Urine)",
    "Gluc0se (Urine)",
    "Ketone",
    "Ket0ne",
    "Blood (Urine)",
    "Bl0od (Urine)",
    "Nitrite",
    "N1trite",
    "Leukocyte Esterase",
    "Leuk0cyte Esterase",
    "WBC (Urine)",
    "RBC (Urine)",
    "Bacteria",
    "Bacter1a",
    "Epithelial Cells",
    "Ep1thelial Cells",
    "Casts",
    "Ca5ts",
    "Crystals",
    "Cry5tals",
]




TEST_SECTIONS = [
"Hematology",
"Haematology",
"Complete Blood Count",
"CBC",
"Differential Count",
"White Blood Cell Differential",
"Peripheral Blood Smear",
"Biochemistry",
"Clinical Chemistry",
"Chemistry",
"Comprehensive Metabolic Panel",
"CMP",
"Basic Metabolic Panel",
"BMP",
"Electrolyte Panel",
"Renal Function Panel",
"Liver Function Panel",
"Hepatic Panel",
"Lipid Panel",
"Lipid Profile",
"Cardiac Markers",
"Cardiac Enzymes",
"Endocrinology",
"Hormone Panel",
"Thyroid Panel",
"Reproductive Endocrinology",
"Adrenal Function",
"Pituitary Function",
"Immunology",
"Serology",
"Autoimmune Panel",
"Rheumatology Panel",
"Allergy Panel",
"Infectious Disease",
"Microbiology",
"Bacteriology",
"Virology",
"Mycology",
"Parasitology",
"Culture and Sensitivity",
"Antimicrobial Susceptibility",
"Urinalysis",
"Urine Analysis",
"UA",
"Coagulation Studies",
"Hemostasis Panel",
"Coagulation Profile",
"Thrombophilia Screen",
"Pathology",
"Anatomic Pathology",
"Surgical Pathology",
"Cytopathology",
"Cytology",
"Histopathology",
"Toxicology",
"Drug Monitoring",
"Therapeutic Drug Monitoring",
"TDM",
"Toxicology Screen",
"Drug Screen",
"Tumor Markers",
"Oncology Markers",
"Cancer Markers",
"Nutritional Markers",
"Iron Studies",
"Vitamin Studies",
"Stool Analysis",
"Fecal Analysis",
"CSF Analysis",
"Cerebrospinal Fluid Analysis",
"Body Fluid Analysis",
"Special Chemistry",
"Point-of-Care Testing",
"POCT",
"Newborn Screening",
"Genetic Testing",
"Molecular Diagnostics",
"Flow Cytometry",
"Blood Bank",
"Transfusion Medicine",
"HLA Typing",
"Prenatal Screening",
"Carrier Screening"
]


TEST_RESULTS = [
    "yellow", "clear", "negative", "negat",
    "seen", "not", "rare", "none",
]

TEST_UNITS = [
    "/", "mmhg", "kpa", "%", "^", "µ",
]

TEST_TITLES = [
    "test", "result", "unit"
]

TEST_METHODS = [
    "elisa", "ecl", "clia", "ita"
]

TEST_NOTES = [
        "low", "high", "normal", "abnormal"
]


TEST_REFERENCES = ['≥', '≤', '>', '<', "up to", "men", "women", "less then", "use only",
                    "borderline", "child", "age ", "newborn" ,"infant", "toddler", "adolescent", "adult", 
                    "girls", "boys", "male", "female", "elderly"]
